---
name: js-tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: Tests with Node ${{ matrix.node }}
    runs-on: "ubuntu-latest"
    if: |
      github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' ||
      github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        node: ["20", "22", "24"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: >
            ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('package-lock.json') }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: |
          npm ci
          npm run build
          (cd integration/react-native-0.79 && npm install --no-audit --no-fund)
          (cd integration/react-native-0.87 && npm install --no-audit --no-fund)

      - name: Run Tests
        run: npm run test:ci
